
Performing  sentiment analysis on following dataset.Using logistic regression. 


In [1]:
import pandas as pd
import numpy as np
import nltk
from sklearn.datasets import load_files
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import pickle
import re


In [8]:
reviews=load_files("tokens/")

In [10]:
X,y=reviews.data,reviews.target

In [11]:
with open("X.pickle","wb") as f:
    pickle.dump(X,f)

with open("y.pickle","wb") as f:
    pickle.dump(y,f)

In [13]:
with open("X.pickle","rb") as f:
    Xp=pickle.load(f)
    
with open("y.pickle","rb") as f:
    yp=pickle.load(f)

In [14]:
corpus=[]
for i in range(0,len(X)):
    reviews=re.sub(r"\W"," ",str(X[i]))#removing ! like
    reviews=reviews.lower()
    reviews=re.sub(r"\s+[a-z]\s+"," ",reviews)#removing single character a i etc also going to use stopwords later
    reviews=re.sub(r"^[a-z]\s+"," ",reviews)#single char in starting 
    reviews=re.sub(r"\s+"," ",reviews)#extra spaces removing
    corpus.append(reviews)

In [20]:
corpus[0]

' directed by david lynch screenplay by john roach and mary sweeney starring richard farnsworth sissy spacek james cada running time 106 minutes rated pg mfcb reviewed on april 24th 2000 the straight story tells tale that would seem too far fetched to be believed if it hadn actually happened based on true events from the summer of 1994 director david lynch newest film is an unusual choice of project for the man behind sometimes baffling fare like twin peaks and lost highway but the straight story is pleasant and engrossing and is also rare motion picture that dares not only to feature largely elderly cast but also to treat them with considerable respect alvin straight richard farnsworth is 73 years old world war ii veteran who has seen better days his hips are giving out on him and his emphysema is getting worse he lives with his daughter rose sissy spacek who is mildly retarded but bright enough in her own way one stormy night alvin learns from relative that his brother lyle has suffe

In [31]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer(max_features=2000,min_df=3,max_df=0.6,stop_words=stopwords.words("english"))

In [32]:
X=vectorizer.fit_transform(corpus).toarray()

In [33]:
X#bagofwords

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [34]:
from sklearn.feature_extraction.text import TfidfTransformer
transform=TfidfTransformer()
X=transform.fit_transform(X).toarray()

In [35]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.09082542],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)#random state is 0 so we get the same results
#text_train,text_test,sent_train,sent_test

In [39]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1120, 2000)
(1120,)
(280, 2000)
(280,)


In [ ]:
#logistic regression y/(y-1)=a+bx+cx2..n

In [40]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()


In [41]:
classifier.fit(X_train,y_train)#model 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [42]:
predict=classifier.predict(X_test)

In [43]:
predict

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0])

In [51]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,predict)

In [52]:
cm#117 WERE -ve and 113 were +ve and model find it right

array([[117,  20],
       [ 30, 113]], dtype=int64)

In [53]:
cm[0][0]+cm[1][1]

230

In [54]:
230/4  #57.5 acc. 

57.5

In [56]:
117+20+30+113

280

In [57]:
#pickle storing model
with open ("classifier","wb") as f:
    pickle .dump(classifier,f)

Thanks  a lot more improvment is required in training to reach 85% atleast